# syntax=docker/dockerfile:1
FROM osrf/ros:humble-desktop-full

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8

SHELL ["/bin/bash", "-c"]

############################# Base packages ##############################
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update -q && apt-get upgrade -yq && apt-get install -yq --no-install-recommends \
        wget \
        curl \
        git \
        gnupg \
        build-essential \
        vim \
        sudo \
        lsb-release \
        locales \
        bash-completion \
        glmark2 \
        tzdata \
        software-properties-common \
        cmake \
        python3-empy \
        python3-defusedxml \
        python3-rosdep \
        python3-rosinstall-generator \
        python3-vcstools \
        python3-vcstool \
        libboost-all-dev && \
    locale-gen en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

############################# ROS1 sources for source build ##############################
RUN add-apt-repository universe && \
    echo "deb http://packages.ros.org/ros/ubuntu focal main" > /etc/apt/sources.list.d/ros-latest.list && \
    curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -

WORKDIR /root

############################# ROS1 installation (source build) ##############################
RUN mkdir -p /root/Downloads
RUN cd /root/Downloads && \
    wget http://archive.ubuntu.com/ubuntu/pool/universe/h/hddtemp/hddtemp_0.3-beta15-53_amd64.deb && \
    apt-get update -q && \
    apt-get install -yq ./hddtemp_0.3-beta15-53_amd64.deb

RUN cd /root/Downloads && \
    wget https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/base.yaml && \
    sed -i '/focal: \[hddtemp\]/a \    jammy: \[hddtemp\]' base.yaml && \
    sed -i "s|^yaml .*base.yaml$|yaml file:///root/Downloads/base.yaml|" /etc/ros/rosdep/sources.list.d/20-default.list && \
    rosdep update

RUN apt-get update -q && \
    apt-get install -yq --no-install-recommends liburdfdom-headers-dev liburdfdom-dev && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /root/catkin_ws && \
    cd /root/catkin_ws && \
    rosinstall_generator ros_comm rosconsole_bridge actionlib actionlib_msgs geometry_msgs common_msgs tf2_msgs tf2_geometry_msgs visualization_msgs --rosdistro noetic --deps --tar > noetic-ros_comm.rosinstall && \
    mkdir -p src && \
    vcs import --input noetic-ros_comm.rosinstall ./src && \
    apt-get update -q && \
    rosdep install --from-paths ./src --ignore-packages-from-source --rosdistro noetic -y --skip-keys=python3-rospkg

RUN cd /root/catkin_ws/src && \
    mkdir -p /root/Downloads/backup && \
    if [ -d rosconsole ]; then mv rosconsole /root/Downloads/backup/; fi && \
    if [ -d urdf ]; then mv urdf /root/Downloads/backup/; fi && \
    git clone https://github.com/dreuter/rosconsole.git && \
    cd rosconsole && \
    git checkout noetic-jammy && \
    cd /root/catkin_ws/src && \
    git clone https://github.com/dreuter/urdf.git && \
    cd urdf && \
    git checkout set-cxx-version && \
    cd /root/catkin_ws/src

############################# gazebo_msgs (ROS1 source) ##############################
RUN cd /root/catkin_ws/src && \
    git clone -b noetic-devel https://github.com/ros-simulation/gazebo_ros_pkgs.git && \
    cd gazebo_ros_pkgs && \
    find . -mindepth 1 -maxdepth 1 -type d ! -name gazebo_msgs -exec rm -rf {} +

# Unset ROS env vars inherited from osrf/ros:humble-desktop-full so that the
# ROS1 Noetic source build does not detect a conflicting humble environment.
# (The original sobits-user variant relied on `sudo` to wipe these vars.)
RUN cd /root/catkin_ws && \
    unset ROS_DISTRO ROS_VERSION ROS_PYTHON_VERSION AMENT_PREFIX_PATH COLCON_PREFIX_PATH && \
    ./src/catkin/bin/catkin_make_isolated --install --install-space /opt/ros/noetic \
        -DCMAKE_BUILD_TYPE=Release \
        --make-args -j$(nproc)

WORKDIR /root
